# Generated by Django 4.2.27 on 2026-02-03 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iae_code', models.CharField(blank=True, default='', max_length=50)),
                ('rentability', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('proximity_to_urban_center_m', models.IntegerField(default=0)),
            ],
        ),
    ]
