# Generated by Django 4.2.27 on 2026-02-03 21:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='coordinates',
            field=models.JSONField(default=core.models.default_coordinates),
        ),
    ]
