# Generated by Django 4.2.27 on 2026-02-04 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_business_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tipology',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
