# Generated by Django 4.2.27 on 2026-02-04 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_iaecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='tipology',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
